# Generated by Django 3.2 on 2021-10-25 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('summary', models.TextField()),
                ('date_saved', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
